### ISSUE TITLE
Callback-based MongoDB Async Java Driver is deprecated since v3.9

### ISSUE THREAD

**Issue by Tmpod** [fluidsonic/fluid-mongo#1]
I was about to start using KMongo on a new project when I decided to check some documentation on the underlying client and noticed it's deprecated since MongoDB Async/Reactive Java Driver v3.9 (now on 3.11). Here's my source: https://mongodb.github.io/mongo-java-driver/3.11/driver-async/#what-s-new-in-3-9
Maybe this lib should change to wrapping reactive streams?

**Comment by fluidsonic** [comment]
Yes I've noticed that and unfortunately this is not trivial.
I agree that wrapping reactive streams makes most sense. At the same time the library should probably be updated to use Kotlin `Flow` rather than `ReceiveChannel`. I can't work on either at the moment but I have it on my list for when I've got some time for it :)

**Comment by fluidsonic** [comment]
`1.0.0-beta.1` has been released, is based on the Reactive Streams driver and uses Kotlin Flows.

Interestingly the Reactive Streams driver uses the Asynchronous Driver under the hood.
I guess it will be refactored away over time.
